Jakarta update
deepshore/kafka-connect-transform-xml pull request #4
Opened 2024-06-13 11:08 UTC by selamanse

2024-06-13 12:26 UTC, selamanse commented
do not merge before xjc release https://github.com/deepshore/xjc-kafka-connect-plugin/pull/3

2024-06-14 07:10 UTC, Blitzableiter requested changes

2024-06-14 07:10 UTC, Blitzableiter commented on pom.xml
> +                    <target>17</target>
Use ${java.version} here
```suggestion
                    <source>${java.version}</source>
                    <target>${java.version}</target>
```

2024-06-14 07:13 UTC, Blitzableiter approved these changes

2024-06-14 07:36 UTC, merged